[project]
name = "etf"
version = "0.1.0"
description = "Simple eft analysis"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "matplotlib>=3.10.1",
    "python-fasthtml>=0.12.4",
    "scikit-learn>=1.6.1",
    "yfinance>=0.2.54",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.9",
]
[tool.ruff.lint]
ignore = [
    "F405"
]
